// <auto-generated />
namespace ASPProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedserviceandroutemodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedserviceandroutemodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201609132008458_added service and route models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
