// <auto-generated />
namespace ASPProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedpickupdayfromservicemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedpickupdayfromservicemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201609152118158_removed pickup day from service model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
